openapi: 3.0.3
info:
  title: Restaurant Service
  version: 1.0.0
servers:
  - url: http:/localhost:8002
paths:
  /dishes:
    get:
      description: List all dishes from restaurant
      responses:
        "200":
          description: List of Dishes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dish"
    post:
      description: Create new dish
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Dish"
      responses:
        "200":
          description: Dish created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dish"
components:
  schemas:
    Dish:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        ingredients:
          type: array
          items:
            type: string
        price:
          type: number
